#!/bin/bash
###############################################################################
# Name: amc
# Description: amc is the client tool for simplifying shell commands
# Author: John Deng (john.deng@outlook.com)
# Updated: 2017-02-11
###############################################################################

source "${HI_CLI_HOME}/bin/utils"

if [ "${heketi_cli_server}" == "" ]; then
  heketi_cli_server=${HEKETI_CLI_SERVER}
fi
heketi_credential=
if [ "${heketi_user}" != "" ] && [ "${heketi_password}" != "" ]; then
  heketi_credential="--user=${heketi_user} --secret=${heketi_password}"
fi

export heketi_cli="heketi-cli -s ${heketi_cli_server} ${heketi_credential}"

log_debug "heketi_cli: ${heketi_cli}"

hi_alias="${heketi_cli}"

function show_exec_usage() {
  show_version
  echo "usages: "
  echo "  ${hi_app} heketi exec pod=the-pod-id cmd="'"'"ls -l"'"'"  "
  echo "  ${hi_app} heketi exec pod=the-pod-id cmd="'"'"any-shell-command"'"'"  "
}

function exec_command_on_volume() {
  
  log_debug "exec_command_on_volume pv: $1 cmd: $2 "

  if [ "$2" == "" ]; then
    show_pv_usage
    exit
  fi

  # NOTE: assume that glusterfs is deployed on default project
  current_project=$(oc projects | grep "*" | awk '{print $2}')
  if [ "$current_project" != "default" ]; then
    oc project default
  fi 

  volume=$(oc describe pv $1 | grep Path | awk '{print $2}' | sed s/vol_//g) 
  cmd=$2

  log_debug "volume: $volume"

  # get all glusterfs pods
  glusterfs_pods=$(oc get po -n default | grep glusterfs | awk '{print $1}')

  if [ "$volume" != "" ] ; then
    
    # get all volume path
    volumes=$(awk "/${volume}/,/Name/" <<<  "$(${heketi_cli} topology info)" | grep Path | awk '{print $2}')
    
    # get all glusterfs pods
    glusterfs_pods=$(oc get po -n default | grep glusterfs | awk '{print $1}')

    while read p; do
      oc rsh $p <<EOF
      echo pod: $p
      echo "$volumes" | while read vol; do
        if [ -d "\${vol}" ]; then
          final_cmd="$(echo ${cmd} | sed 's/{}/\${vol}/g')"
          echo "command: \${final_cmd}"
          \${final_cmd}
        fi
      done
EOF
    done <<< "$glusterfs_pods"
  fi

  oc project $current_project
}

function exec_command() {
  
  log_info "execute command on pod: $1 cmd: $2"

  if [ "$2" == "" ] || [ "$1" == "" ]; then
    show_pv_usage
    exit
  fi

  oc rsh $pod <<EOF
    echo ${cmd}
    ${cmd}
EOF

  oc project $current_project
}

function delete_pv() {
  oc whoami > /dev/null   
  if [ $? != 0 ]; then
    log_error "you are not allowed to delete pv"
    return 1
  fi
  pv_name=$1
  if [ "${pv_name}" == "" ]; 
  then
    log_warn "pv name is null"
    exit
  fi
  if [ "$delete" == "delete" ]; then 
    log_info "deleting pv ${pv_name}, please wait ..."
    pv_info=$(oc get pv ${pv_name} -o json)
    if [ $? == 0 ]; 
    then
      log_debug "${pv_info}"

      parse_json vol_path "${pv_info}" spec glusterfs path
      
      volume=${vol_path/vol_/}
      ${heketi_cli} volume delete ${volume}
      oc delete pv ${pv_name}
    else
      log_warn "pv ${pv_name} not found"
    fi
  fi
}

function delete_pvc() {
  oc whoami > /dev/null   
  if [ $? != 0 ]; then
    log_error "you are not allowed to delete pvc"
    return 1
  fi
  log_debug $pv
  pv_name=$(oc get pvc | grep ${name} | awk '{print $3}')
  log_debug ${pv_name}

  if [ "${pv_name}" != "" ] && [ $(oc get pvc | grep "${pv_name}" | grep "Bound" | wc -l) != 0 ]; 
  then
    delete_pv ${pv_name}
  fi
  log_info  "deleting pvc, name: $name"
  if [ $(oc get pvc | grep ${name} | wc -l) != 0 ]; 
  then
    log_debug "delete pvc $name"
    oc delete pvc ${name}
    log_debug "pvc ${name} is deleted"
  else
    log_warn "pvc ${name} not found"  
  fi
}

function expand_pvc() {
  oc whoami > /dev/null   
  if [ $? != 0 ]; then
    log_error "you are not allowed to expand pvc"
    return 1
  fi
  log_debug $pv
  pv_name=$(oc get pvc | grep ${name} | awk '{print $3}')
  log_debug "pv_name: ${pv_name}"

  log_info  "expanding pvc, name: $name ..."
  res=0
  if [ "${pv_name}" != "" ] && [ $(oc get pvc | grep "${pv_name}" | grep "Bound" | wc -l) != 0 ]; 
  then

    pv_info=$(oc get pv ${pv_name} -o json)
    parse_json vol_path "${pv_info}" spec glusterfs path
    if [ ${size} != 0 ]; then
      log_debug "start expand vol_path: ${vol_path}"
      expand_cli="${heketi_cli} volume expand --expand-size=${size} --volume=${vol_path/vol_/}"
      log_debug "${expand_cli}"
      ${expand_cli}
      res=$?
      log_debug "expanded volume ${vol_path} of pv ${pv_name}"
    fi
  fi

  if [ ${res} == 0 ]; then
    # change pv, pvc
    log_info "changing the capacity of pv and pvc ..."

    parse_json prev_capacity "${pv_info}" spec capacity storage
    log_debug "prev_capacity: ${prev_capacity}"
    prev_capacity_num=${prev_capacity/Gi/}
    log_debug "prev_capacity_num: ${prev_capacity_num}"
    new_capacity=$((prev_capacity_num + size))Gi
    log_debug "new_capacity: ${new_capacity}"

    new_pv_info=$(echo ${pv_info} | sed "s/${prev_capacity}/${new_capacity}/g")
    log_debug "${new_pv_info}"
    echo ${new_pv_info} | oc apply -f -

    sleep 1

    pvc_info=$(oc get pvc ${name} -o json)
    new_pvc_info=$(echo ${pvc_info} | sed "s/${prev_capacity}/${new_capacity}/g")
    log_debug "${new_pvc_info}"
    echo ${new_pvc_info} | oc apply -f -

  else
    log_debug "failed to expand" 
    return 1 
  fi
}

function create_pv() {
  log_debug "create_pv is called"

  oc whoami > /dev/null
  if [ $? != 0 ]; then
    log_error "you are not allowed to create pv"
    return 1
  fi

  log_info "creating pv, please wait ..."

  mkdir -p ${module_dir}/endpoints
  ep_file="${module_dir}/endpoints/endpoints.json"
  
  ${heketi_cli} volume create --size=${size} --persistent-volume --persistent-volume-endpoint=heketi-storage-endpoints > ${ep_file}

  ep=$(cat ${ep_file})

  log_debug "created pv with ep: ${ep}"

  if [ "${ep}" == "" ]; then
    log_error "volume is not created"
    return 1
  fi

  parse_json pv_name "${ep}" metadata name

  if [ $? != 0 ]; then
    log_error "wrong endpoint"
    return 2
  fi

  log_info "creating endpoint"
  oc create -f ${ep_file}

  parse_json vol_path "${ep}" spec glusterfs path

  # rm -rf ${ep_file}
  mkdir -p ${working_dir}/endpoints/
  mv ${ep_file} ${working_dir}/endpoints/${vol_path}.json

  if [ "$cmd" == "" ]; then
    cmd="chmod 777 {}"
  fi
  if [ "$uid" != "" ]; then
    cmd="chown ${uid}:${uid} {}"
  fi
  log_debug "exec_command_on_volume ${pv_name} ${cmd}"
  exec_command_on_volume "${pv_name}" "${cmd}"
}

function create_pvc() {
  oc whoami > /dev/null   
  if [ $? != 0 ]; then
    log_error "you are not allowed to create pvc"
    return 1
  fi
  echo "create pvc name: ${name} size: ${size}"
  if [ "${mode}" == "" ]; then
    mode="ReadWriteMany"
  fi  

  oc create -f - <<_EOF_
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${name}
spec:
  accessModes:
  - ${mode}
  resources:
    requests:
      storage: ${size}Gi
status: {}
_EOF_

  create_endpoints

}

function create_endpoints() {
  if [ "${heketi_endpoints}" == "" ]; then
    log_error "error: heketi_endpoints is empty"
    return -1
  fi
  if [ $(oc get ep | grep heketi-storage-endpoints | wc -l) == 0 ]; then
    arr=($heketi_endpoints)
    endpoints=""
    for i in "${arr[@]}"; do
      if [ "${endpoints}" == "" ]; then
        endpoints="${endpoints}  - ip: ${i}"
      else
        endpoints=$(printf "${endpoints}\n  - ip: ${i}")
      fi
    done

    heketi_ep="$(cat <<-EOF
apiVersion: v1
kind: Endpoints
metadata:
  name: heketi-storage-endpoints
subsets:
- addresses:
${endpoints}
  ports:
  - port: 1
EOF
)"

glusterfs_svc="$(cat <<-EOF
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
EOF
)"

    log_debug "${heketi_ep}"
    log_debug "${glusterfs_svc}"

    oc create -f - <<_EOF_
apiVersion: v1
kind: Endpoints
metadata:
  name: heketi-storage-endpoints
subsets:
- addresses:
${endpoints}
  ports:
  - port: 1
_EOF_
    
    oc create -f - <<_EOF_
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
_EOF_
    

  fi
}

###############################################################################
# main entry
function main() {
  #log "main loop ..."

  if [ "$version" == "version" ]; then 
    show_version
    exit
  fi

  if [ "$pv" != "" ]; then
    if [ "$help" == "help" ]; then 
      show_pv_usage
      exit
    fi

    network_option=''
    if [ "$net" == "vpn" ] || [ "$vpn" == "vpn" ] ; then
      network_option=" -l network=vpn "
    fi

    if [ "$delete" == "delete" ] && [ "$pv" != "pv" ]; then 
      delete_pv
    elif [ "$create" == "create" ] && [ $size > 0 ] ; then
      create_pv
    elif [ "$edit" == "edit" ] && [ "$cmd" != "" ] ; then
      exec_command_on_volume "$pv" "$cmd"
    fi
  fi

  if [ "$pvc" != "" ]; then
    if [ "$create" == "create" ] && [ $size > 0 ] ; then
      create_pvc
    elif [ "$delete" == "delete" ]; then
      echo  "delete pvc, name: $name"
      
      if [ "$pv" = "pv" ]; then
        pv=$(oc get pvc | grep $name | awk '{print $3}')
        if [ "$pv" != "" ]; then
          delete_pv
        fi
      fi
      oc delete pvc $name
    fi

  fi

  if [ "$exec" != "" ]; then
    log "debug"
    if [ "$help" == "help" ]; then 
      log "debug"
      show_exec_usage
    elif [ "$cmd" != "" ] && [ "$pod" != "" ] ; then
      log "debug"
      exec_command "$pod" "$cmd"
    elif [ "$cmd" != "" ] && [ "$pods" != "" ] ; then
      log "debug"
      exec_command "$pods" "$cmd" "batch"
    fi
  fi
}
