#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: 2017-02-11
###############################################################################

source "${HI_CLI_HOME}/bin/colors"

cmd="hi heketi"

function show_usage() {
  echo "usages: "
  echo ""
  echo "crate pv, volume size 10G:  "
  echo "  ${cmd} create pv size=10 "
  echo "create pv, volume size 8G, then create pvc, name my-pvc-name, uid is 27, the uid is the user id of target pod"
  echo "  ${cmd} create pv size=8 pvc name=my-pvc-name uid=27"
  echo "delete pv, name my-pv-name, (run oc get pv to query pv name)"
  echo "  ${cmd} delete pv name=my-pv-name"
  echo "delete pv and pvc, pvc name is my-pvc-name"
  echo "  ${cmd} delete pvc name=my-pvc-name"
  echo "exec command line inside glusterfs by specify pv name"
  echo "  ${cmd} exec pv name=my-pvc-name cmd='ls -l {}' "
  echo "  (NOTES: above example exec the ls -l command, {} is the pv ) "
}